### ISSUE TITLE
Broken link to config file format

### ISSUE THREAD

**Issue by houshuang** [jgoerzen/configfile#8]
The link to the file format in the wiki, which seems pretty crucial, is currently broken.

Thanks!

**Comment by enolan** [comment]
All the docs are missing. According to the Hackage page, they didn't fail, they were just never generated. @jgoerzen, you can upload a set built locally with Neil Mitchell's "neil" tool. Here's a link: http://neilmitchell.blogspot.com/2014/10/fixing-haddock-docs-on-hackage.html

**Comment by jgoerzen** [comment]
Everything is good right now.
